---
title: "code"
author: "Masha"
date: "2024-05-01"
output: html_document
---

Downloading the data in **data** folder (hidden chunk)

```{r downloading, include=FALSE}
download.file(url="https://raw.githubusercontent.com/cambiotraining/reproducibility-training/master/data/gapminder_data.csv", destfile="data/gapminder_data.csv")
```

```{r load-data, message=FALSE}
#load tidyverse library
library(tidyverse) # used for data manipulation
library(rmarkdown) # used for paged_table function
library(kableExtra) # used for table
library(ggpubr) #used for ggarrange function 

#read file into R
pop_data <- read_csv("data/gapminder_data.csv")

#create a table with data from European countries in 2007 showing the countries 
#with the largest life expectancy at the top 
euro_data_tbl <- pop_data %>% 
                    filter(continent == "Europe" & year == 2007) %>% 
                    select(-continent, -year) %>% 
                    arrange(desc(lifeExp)) %>% 
                    rename(Country = country, "Population Size" = pop, 
                      "Life Expectancy" = lifeExp, "GDP" = gdpPercap)
    
```

```{r kbl}
euro_data_tbl %>% 
          kbl() %>% 
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F, fixed_thead = list(enabled =T, background = "red")) #it works in visual but not in the website :()
```

```{r paged-table}
paged_table(euro_data_tbl)
```

This is the new text to master github even more. I am just making changes in local computer to see them on github.
